const bootcamperTable = [{
	firstname: 'Carmel Daniel',
	lastname: 'Corseanschi',
	bootcamperid: 10,
	frequency: 3,
	startdate: '2021-07-26',
},
];
const reflections = [
	{
		bootcamperid: 10,
		reflection: 'Really enjoyed the day, the vibe is good, high morale, we definitely need to work a bit more on the design of the project.    It feels like there is so much more to work on , maybe a bit overwhelming but slowly and with perseverance we keep going forward',
		accessible: true,
		topics: [
			{ topic: 'primitive types', rating: 4 },
			{ topic: 'complex types', rating: 2 },
			{ topic: 'pass by reference', rating: 3 },
			{ topic: 'cognitive load', rating: 5 },
		],
		confidence: 4,
		grateful: 'how awesome this course is',
		improvements: 'complex types, computational thinking',
		overallFeeling: 5,
	},
	{
		bootcamperid: 10,
		reflection: 'Another day went by learning loads of toads',
		accessible: true,
		topics: [
			{ topic: 'closures', rating: 1 },
			{ topic: 'recursiveness', rating: 4 },
			{ topic: 'OOP', rating: 3 },
			{ topic: 'currying', rating: 1 },
		],
		confidence: 2,
		grateful: 'Liz Kaufman',
		improvements: 'closures,currying',
		overallFeeling: 3,
	},
	{
		bootcamperid: 10,
		reflection: 'Cannot find anything else to add',
		accessible: true,
		topics: [
			{ topic: 'generator functions', rating: 1 },
			{ topic: 'events', rating: 2 },
			{ topic: 'authentication', rating: 1 },
			{ topic: 'useReducer', rating: 4 },
		],
		confidence: 3,
		grateful: 'the support given out',
		improvements: 'generator functions,authentication',
		overallFeeling: 3,
	},
	{
		bootcamperid: 10,
		reflection: 'Not in the mood for reflecting',
		accessible: true,
		topics: [
			{ topic: 'firebase', rating: 1 },
			{ topic: 's3 buckets', rating: 4 },
			{ topic: 'serverless', rating: 2 },
			{ topic: 'amplify', rating: 4 },
		],
		confidence: 5,
		grateful: 'being alive , the sun , water',
		improvements: 'firebase, firing events',
		overallFeeling: 5,
	},
];
